[package]
name = "png"
version = "0.1.0"
edition = "2021"
default-run = "png"

[[bin]]
name = "profile"
path = "./bin/profile.rs"


[profile.release]
debug = true

[dependencies]
crc32fast = "1.4.2"
flate2 = "1.0.35"

anyhow = "1.0.94"
minifb = "0.27.0"