[package]
name = "png"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
flate2 = "1.0.35"
minifb = "0.27.0"
